[versions]
registrate = "MC1.20-1.3.11"
jei = "15.20.0.105"

[libraries]
registrate = { module = "com.tterrag.registrate:Registrate", version.ref = "registrate" }
jei-common-api = { module = "mezz.jei:jei-1.20.1-common-api", version.ref = "jei" }
jei-forge-api = { module = "mezz.jei:jei-1.20.1-forge-api", version.ref = "jei" }
jei-forge-impl = { module = "mezz.jei:jei-1.20.1-forge", version.ref = "jei" }

[bundles]
jei = ["jei-common-api", "jei-forge-api", "jei-forge-impl"]