modLoader="javafml"
loaderVersion="${loader_version_range}"
license="GNU LGPLv3.0-Only"

[[mods]]

modId="list"
version="3.0.5"
displayName="list"
authors="y271727uy"
description='''The item core mod for Farmer's Ranch: Pastoral Serenade'''

[[dependencies.list]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.list]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.list]]
    modId="kubejs"
    mandatory=true
    versionRange="[2001.6.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.list]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.20.1-1.2.7]"
    ordering="NONE"
    side="BOTH"



